import AppKit
import Observation

/// One thing that was copied.
struct ClipboardEntry: Identifiable {
    enum Content {
        case text(String)
        case image(NSImage)
    }

    let id = UUID()
    let content: Content
}

/// The last few things you copied. Kept in memory only, never written to disk, and copies that
/// password managers mark as concealed or transient are skipped.
@MainActor
@Observable
final class ClipboardHistory {
    /// How many copies are kept unless Settings says otherwise.
    static let limit = 10
    /// What Settings may choose: none (history off), or this many.
    static let limits = [0, 10, 25, 50]

    /// How many copies to keep. Zero is off: nothing is recorded, and nothing is watching the pasteboard.
    private(set) var capacity = ClipboardHistory.limit

    private(set) var entries: [ClipboardEntry] = []

    @ObservationIgnored private var lastChangeCount = NSPasteboard.general.changeCount
    @ObservationIgnored private var timer: Timer?

    private static let privateTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Sets how many copies to keep. Zero (off) stops watching the pasteboard and forgets what was kept; another
    /// number starts it again if it was running.
    func setCapacity(_ count: Int, running: Bool = true) {
        capacity = Self.limits.contains(count) ? count : Self.limit
        if capacity == 0 {
            stop()
            entries.removeAll()
        } else {
            if entries.count > capacity { entries.removeLast(entries.count - capacity) }
            if running { start() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    var isWatching: Bool { timer != nil }

    func start() {
        guard timer == nil, capacity > 0 else { return }
        // The pasteboard has no change notification, so compare its change count.
        let timer = Timer(timeInterval: 0.7, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // Lets macOS fire it with other wakeups instead of on its own.
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func poll(pasteboard: NSPasteboard = .general) {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let types = pasteboard.types ?? []
        guard !types.contains(where: Self.privateTypes.contains) else { return }

        if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        {
            record(.text(text))
        } else if let image = NSImage(pasteboard: pasteboard) {
            record(.image(image))
        }
    }

    func record(_ content: ClipboardEntry.Content) {
        guard capacity > 0 else { return }
        // Copying the same text again moves it to the top instead of repeating it.
        if case .text(let text) = content {
            entries.removeAll { if case .text(let other) = $0.content { other == text } else { false } }
        }
        entries.insert(ClipboardEntry(content: content), at: 0)
        if entries.count > capacity { entries.removeLast(entries.count - capacity) }
    }

    /// Puts an entry back on the pasteboard without recording it as a new copy.
    func copy(_ entry: ClipboardEntry, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        switch entry.content {
        case .text(let text): pasteboard.setString(text, forType: .string)
        case .image(let image): pasteboard.writeObjects([image])
        }
        lastChangeCount = pasteboard.changeCount
    }

    /// Puts text on the pasteboard without recording it as a new copy.
    func copyText(_ text: String, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }

    func remove(_ entry: ClipboardEntry) {
        entries.removeAll { $0.id == entry.id }
    }

    func clear() {
        entries.removeAll()
    }
}
